# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f96801b8a084e2d0e7e2efa0a21728032e07c6420f86911ee590334cb19648e8c6d9a556c2f6aa2636197554cccfb2b42bea5df9216f321b81baa4038f7997f

test:
  secret_key_base: a9bbc54cd791cdc542b9ffb5a221583103b0c10808722f8ba25a708898995fd01589e9169a263c4cd347d61ea80f2470cb48a38ff34ede2573b78fb7689048b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
